Header Implementation
edwartexe/html-css-training pull request #1
Opened 2020-11-06 14:37 UTC by edwartexe

This PR implements the header feature for the frontend training

2020-11-06 20:53 UTC, rhonaldomaster commented on styles.css
> +.mainNav{
@edwartexe do not write class names in that way (mixing uppercase and lowercase). If you need to separate words, use hyphens. Also, write a blank space between the rule and the bracket. In that way, you can avoid deleting brackets by mistake.
```suggestion
.main-nav {
```

2020-11-06 20:56 UTC, rhonaldomaster commented on styles.css
> +.closed.menu-items-toggle, .closed .home-logo,.closed .phone-link img{
Avoid using tag names for styling. If possible, use a class. Also, if you have more than a rule you can write each one in a line to have good code readability.
```suggestion
.closed.menu-items-toggle,
.closed .home-logo,
.closed .phone-link-img {
```

2020-11-06 20:57 UTC, rhonaldomaster commented on styles.css
> +    position: relative;
Use 2-space indentation 
```suggestion
  position: relative;
```

2020-11-06 20:59 UTC, rhonaldomaster commented on styles.css
> +#nav-items .contactLink{
**DON'T** use ids for styling.

2020-11-06 21:01 UTC, rhonaldomaster commented on styles.css
> + h1 {
Have into account that if you apply styles to a tag, the styles will be applied to every tag in the page. If you only need to style one element, use classes

2020-11-06 21:02 UTC, rhonaldomaster commented on styles.css
> + @media only screen and (min-width: 500px) {
Be aware of indentation, that can help you and others to understand your code better

2020-11-06 21:04 UTC, rhonaldomaster commented on styles.css
> +  .main-header img{display: none;}
Avoid using one-line rules. In that way your code readability will improve
```suggestion
  .main-header img {
    display: none;
  }
```

2020-11-06 21:09 UTC, rhonaldomaster commented
@edwartexe we normally use the assets folder to include scripts, styles, images and fonts. In that way we know where the files are. Then we create the folders inside the assets folders. For instance, `assets/styles`.

I see you don't have the GTWalsheim font. When a design has a font, you must include it. If the font is free, you can simply download it. If not, you tell the designer to give you the font. Regarding the font format, use woff or woff2. These formats are for web.

2020-11-06 21:29 UTC, edwartexe commented on styles.css
> + h1 {
in most cases there should only exist one instance of h1 per page so i tought this would be allright but i will take it into account

2020-11-06 21:33 UTC, rhonaldomaster commented on index.html
> +<head>
Please use 2-spaces indentation

2020-11-06 21:35 UTC, rhonaldomaster commented on index.html
> +        <a href="javascript:void(0);" class="burger-icon menu-items-toggle" id="nav-itemsToggle" onclick="myFunction()">
If you have an element that doesn't redirect you, but will perform an action, you can use a button for that
```suggestion
        <button class="burger-icon menu-items-toggle" id="nav-itemsToggle" onclick="myFunction()">
```

2020-11-06 21:47 UTC, rhonaldomaster commented
I almost forget about it.
Remember to minimize/optimize images. You can use apps like imageoptim or services like tinypng.com

2020-11-12 19:44 UTC, rhonaldomaster commented
@edwartexe this PR contains .DS_Store files from OSX. You can avoid uploading them by using a .gitignore file. You can search in the web examples or use this webpage https://www.toptal.com/developers/gitignore

2020-11-12 19:45 UTC, rhonaldomaster commented
@edwartexe you can also optimize images using:
For SVG: https://imageoptim.com/mac
For PNG, JPEG: https://tinypng.com/

2020-11-12 19:47 UTC, rhonaldomaster commented on assets/styles/styles.css
> +  }
@edwartexe be aware of indentation 😄

2020-11-12 19:48 UTC, rhonaldomaster commented on assets/styles/styles.css
> +  font-family: 'GTWalsheim','';
Is there something else overwriting the font family? If not, this can be omitted
```suggestion
```

2020-11-12 19:50 UTC, rhonaldomaster commented on assets/styles/styles.css
> +
I see that you have some big blank spaces like this one. These spaces don't help with your code readability

2020-11-12 19:51 UTC, rhonaldomaster commented on assets/styles/styles.css
> +.third-title{
Until reaching this line you were using a space before the bracket. What happened @edwartexe ? 😄 
```suggestion
.third-title {
```

2020-11-12 19:54 UTC, rhonaldomaster requested changes

2020-11-12 19:54 UTC, rhonaldomaster commented on index.html
> +<head>
Still unresolved @edwartexe

2020-11-12 22:16 UTC, edwartexe commented on assets/styles/styles.css
> +
i mostly leave big spaces to separate sections so they are visible on the scroll's zoom

i will remove them once im finished. or is there a better way of visualy separating css rules in the same file?

2020-11-12 22:17 UTC, edwartexe commented on index.html
> +<head>
im not sure i understand, i added correct indentatio to the html file on the body but do you mean i should indent everything inside <html>?

2020-11-13 14:09 UTC, rhonaldomaster commented on assets/styles/styles.css
> +
You can use comments for that. For instance
```suggestion
/**
Nav section
**/
```
And you can have the readability you want

2020-11-13 14:14 UTC, rhonaldomaster commented on index.html
> +	<head>
@edwartexe I'm still seeing the bad indentation in this file. This is a screenshot taken from the branch file in github.
![image](https://user-images.githubusercontent.com/16655413/99081276-91689280-2590-11eb-819b-14b2848f281d.png)

2020-11-13 14:16 UTC, rhonaldomaster commented on slick-1.8.1/CONTRIBUTING.markdown
> +## Submitting issues
You don't need to include the full slick repository. Check their documentation, you only need three files:
![image](https://user-images.githubusercontent.com/16655413/99081495-e73d3a80-2590-11eb-9d5b-d32740722fe3.png)

2020-11-24 22:11 UTC, closed without merging